# Generated by Django 4.0.4 on 2022-05-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_product_farmername_and_more'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Active_Shipping_Address',
            field=models.ForeignKey(blank=True, limit_choices_to={'phone': models.CharField(max_length=20)}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_status',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=500),
        ),
    ]
