# Generated by Django 4.0.4 on 2022-05-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_product_farmername_and_more'),
        ('account', '0003_alter_user_active_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Active_Shipping_Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.shippingaddress'),
        ),
    ]
