# Generated by Django 4.0.4 on 2022-05-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=100)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/category')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('states', models.CharField(choices=[('Abia', ' Abia'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT - Abuja', 'FCT - Abuja'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('ndo', 'ndo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('intra_state_shipping_fee', models.CharField(max_length=20)),
                ('inter_state_shipping_fee', models.CharField(max_length=20)),
                ('prod_image', models.ImageField(upload_to='photos/goods')),
                ('stock', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('farmername', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.merchant')),
                ('product_catgeory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.category')),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.storelocation')),
            ],
        ),
    ]
