# Generated by Django 4.0.4 on 2022-05-12 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('tracking_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('Transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Awaiting Packaging', 'Awaiting Packaging'), ('Packaged', 'Packaged'), ('On Delivery', 'On Delivery'), ('Delivered', 'Delivered')], default='Awaiting Packaging', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
