# Generated by Django 4.0.4 on 2022-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='sold_by',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
